#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesTracker
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Expenses_Tracker")]
	public partial class ExpensesEntityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHUSBAND_WIFE(HUSBAND_WIFE instance);
    partial void UpdateHUSBAND_WIFE(HUSBAND_WIFE instance);
    partial void DeleteHUSBAND_WIFE(HUSBAND_WIFE instance);
    #endregion
		
		public ExpensesEntityDataContext() : 
				base(global::ExpensesTracker.Properties.Settings.Default.Expenses_TrackerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExpensesEntityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpensesEntityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpensesEntityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpensesEntityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HUSBAND_WIFE> HUSBAND_WIFEs
		{
			get
			{
				return this.GetTable<HUSBAND_WIFE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HUSBAND_WIFE")]
	public partial class HUSBAND_WIFE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HUSBAND_WIFE_ID;
		
		private string _HUSBAND_WIFE_TYPE;
		
		private System.Nullable<int> _HUSBAND_WIFE_AMT;
		
		private string _HUSBAND_WIFE_DATE;
		
		private int _HUSBAND_WIFE_TYPE_ID;
		
		private System.Nullable<int> _EXPENSES_CATEGORY_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHUSBAND_WIFE_IDChanging(int value);
    partial void OnHUSBAND_WIFE_IDChanged();
    partial void OnHUSBAND_WIFE_TYPEChanging(string value);
    partial void OnHUSBAND_WIFE_TYPEChanged();
    partial void OnHUSBAND_WIFE_AMTChanging(System.Nullable<int> value);
    partial void OnHUSBAND_WIFE_AMTChanged();
    partial void OnHUSBAND_WIFE_DATEChanging(string value);
    partial void OnHUSBAND_WIFE_DATEChanged();
    partial void OnHUSBAND_WIFE_TYPE_IDChanging(int value);
    partial void OnHUSBAND_WIFE_TYPE_IDChanged();
    partial void OnEXPENSES_CATEGORY_IDChanging(System.Nullable<int> value);
    partial void OnEXPENSES_CATEGORY_IDChanged();
    #endregion
		
		public HUSBAND_WIFE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSBAND_WIFE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HUSBAND_WIFE_ID
		{
			get
			{
				return this._HUSBAND_WIFE_ID;
			}
			set
			{
				if ((this._HUSBAND_WIFE_ID != value))
				{
					this.OnHUSBAND_WIFE_IDChanging(value);
					this.SendPropertyChanging();
					this._HUSBAND_WIFE_ID = value;
					this.SendPropertyChanged("HUSBAND_WIFE_ID");
					this.OnHUSBAND_WIFE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSBAND_WIFE_TYPE", DbType="VarChar(10)")]
		public string HUSBAND_WIFE_TYPE
		{
			get
			{
				return this._HUSBAND_WIFE_TYPE;
			}
			set
			{
				if ((this._HUSBAND_WIFE_TYPE != value))
				{
					this.OnHUSBAND_WIFE_TYPEChanging(value);
					this.SendPropertyChanging();
					this._HUSBAND_WIFE_TYPE = value;
					this.SendPropertyChanged("HUSBAND_WIFE_TYPE");
					this.OnHUSBAND_WIFE_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSBAND_WIFE_AMT", DbType="Int")]
		public System.Nullable<int> HUSBAND_WIFE_AMT
		{
			get
			{
				return this._HUSBAND_WIFE_AMT;
			}
			set
			{
				if ((this._HUSBAND_WIFE_AMT != value))
				{
					this.OnHUSBAND_WIFE_AMTChanging(value);
					this.SendPropertyChanging();
					this._HUSBAND_WIFE_AMT = value;
					this.SendPropertyChanged("HUSBAND_WIFE_AMT");
					this.OnHUSBAND_WIFE_AMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSBAND_WIFE_DATE", DbType="VarChar(100)")]
		public string HUSBAND_WIFE_DATE
		{
			get
			{
				return this._HUSBAND_WIFE_DATE;
			}
			set
			{
				if ((this._HUSBAND_WIFE_DATE != value))
				{
					this.OnHUSBAND_WIFE_DATEChanging(value);
					this.SendPropertyChanging();
					this._HUSBAND_WIFE_DATE = value;
					this.SendPropertyChanged("HUSBAND_WIFE_DATE");
					this.OnHUSBAND_WIFE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUSBAND_WIFE_TYPE_ID", DbType="Int NOT NULL")]
		public int HUSBAND_WIFE_TYPE_ID
		{
			get
			{
				return this._HUSBAND_WIFE_TYPE_ID;
			}
			set
			{
				if ((this._HUSBAND_WIFE_TYPE_ID != value))
				{
					this.OnHUSBAND_WIFE_TYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._HUSBAND_WIFE_TYPE_ID = value;
					this.SendPropertyChanged("HUSBAND_WIFE_TYPE_ID");
					this.OnHUSBAND_WIFE_TYPE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPENSES_CATEGORY_ID", DbType="Int")]
		public System.Nullable<int> EXPENSES_CATEGORY_ID
		{
			get
			{
				return this._EXPENSES_CATEGORY_ID;
			}
			set
			{
				if ((this._EXPENSES_CATEGORY_ID != value))
				{
					this.OnEXPENSES_CATEGORY_IDChanging(value);
					this.SendPropertyChanging();
					this._EXPENSES_CATEGORY_ID = value;
					this.SendPropertyChanged("EXPENSES_CATEGORY_ID");
					this.OnEXPENSES_CATEGORY_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
