CREATE PROCEDURE [dbo].[HUSBANDWIFEPROCEDURE]
AS
BEGIN
	SELECT HUSBAND_WIFE_ID, HUSBAND_WIFE_TYPE_VALUE, HUSBAND_WIFE_AMT, HUSBAND_WIFE_DATE, ISNULL(A.EXPENSES_CATEGORY_ID,0) EXPENSES_CATEGORY_ID, B.EXPENSES_CATEGORY_NAME FROM DBO.HUSBAND_WIFE A
LEFT JOIN EXPENSES_CATEGORY B
ON A.EXPENSES_CATEGORY_ID = B.EXPENSES_CATEGORY_ID 
WHERE EXPENSES_CATEGORY_TABLE_VALUE = 'HUWF' OR A.EXPENSES_CATEGORY_ID IS NULL ORDER BY HUSBAND_WIFE_ID DESC
END
