CREATE PROCEDURE [DBO].[SHARE_TRACKER_PROCEDURE_DIVIDEND]
@USERID INT
AS
Select A.*, B.SHARES_NAME from SHARE_DIVIDEND A
left JOIN SHARES_TRACKER_HEADER B
on A.SHARES_TRACKER_HEADER_ID = B.SHARES_TRACKER_HEADER_ID
WHERE B.USER_ID = @USERID
GO
