CREATE PROCEDURE [SHARE_TRACKER_PROCEDURE_EXTRA_INCOMING_OUTGOING]
@USERID INT
AS
SELECT EXTRA_INCOMING_OUTGOING_ID, AMOUNT, 
INCOMING_OUTGOING_DESCRIPTION,INCOMING_OUTGOING_CODE_ID, 
INCOMING_OUTGOING_CODE_VALUE, INCOMING_OUTGOING_DATE,
USER_ID FROM dbo.EXTRA_INCOMING_OUTGOING
WHERE USER_ID = @USERID
GO