CREATE PROCEDURE [dbo].[SHARE_TRACKER_PROCEDURE_EXTRA_CHARGES]
@USERID INT
AS
Select SHARES_EXTRA_CHARGES_DESCRIPTION,SHARES_EXTRA_CHARGES_AMT,SHARES_CHARGES_DATE,
SHARES_NAME,EXT.SHARES_TRACKER_HEADER_ID , IS_CONSIDER, SHARES_TRACKER_EXTRA_CHARGES_ID
from [dbo].[SHARES_TRACKER_EXTRA_CHARGES] EXT
LEFT JOIN [dbo].[SHARES_TRACKER_HEADER] HDR
ON EXT.SHARES_TRACKER_HEADER_ID = HDR.SHARES_TRACKER_HEADER_ID
Where EXT.USER_ID = @USERID
GO