CREATE TABLE [DBO].[CODE_ID](
	[CODE_ID] [INT] NOT NULL,
	[CODE_DESCRIPTION] [VARCHAR](1000) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
