CREATE TABLE [DBO].[EXPENSES_TRACKER](
	[EXPENSES_TRACKER_ID] [INT] IDENTITY(1,1) NOT NULL,
	[EXPENSES_ITEM] [VARCHAR](500) NOT NULL,
	[EXPENSES_DATE] date NOT NULL,
	[EXPENSES_AMT] [INT] NOT NULL,
	[EXPENSES_CATEGORY_ID] [INT] NULL,
	[EXPENSES_TYPE_ID] [INT] NOT NULL,
	[EXPENSES_TYPE_VALUE] [VARCHAR](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EXPENSES_TRACKER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [DBO].[EXPENSES_TRACKER] ADD FOREIGN KEY([EXPENSES_CATEGORY_ID])
REFERENCES [DBO].[EXPENSES_CATEGORY] ([EXPENSES_CATEGORY_ID])
GO