CREATE TABLE [dbo].[EXTRA_INCOMING_OUTGOING](
	[EXTRA_INCOMING_OUTGOING_ID] [int] IDENTITY(1,1) NOT NULL,
	[AMOUNT] [decimal](6, 2) NOT NULL,
	[INCOMING_OUTGOING_CODE_ID] [int] NOT NULL,
	[INCOMING_OUTGOING_CODE_VALUE] [varchar](100) NOT NULL,
	[INCOMING_OUTGOING_DATE] [date] NOT NULL,
	[USER_ID] [int] NULL,
	[INCOMING_OUTGOING_DESCRIPTION] [varchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[EXTRA_INCOMING_OUTGOING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[EXTRA_INCOMING_OUTGOING]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[Login_Info] ([Login_Info_Id])
GO
