CREATE TABLE [DBO].[LOGIN_INFO](
	[LOGIN_INFO_ID] [INT] IDENTITY(1,1) NOT NULL,
	[USERNAME] [VARCHAR](200) NOT NULL,
	[PASSWORD] [VARCHAR](100) NOT NULL,
	[FIRST_NAME] [VARCHAR](100) NOT NULL,
	[LAST_NAME] [VARCHAR](100) NOT NULL,
	[GENDER] [VARCHAR](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LOGIN_INFO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
