CREATE TABLE [dbo].[MUTUAL_FUND_PAYIN_PAYOUT](
	[MUTUAL_FUND_PAYIN_PAYOUT_ID] [int] IDENTITY(1,1) NOT NULL,
	[MUTUAL_FUND_TRANSACTION_CODE_ID] [int] NOT NULL,
	[MUTUAL_FUND_TRANSACTION_CODE_VALUE] [varchar](200) NOT NULL,
	[MUTUAL_FUND_TRANSACTION_AMT] [decimal](8, 2) NOT NULL,
	[MUTUAL_FUND_TRANSACTION_DATE] [date] NULL,
	[USER_ID] [int] NOT NULL,
	[DEMAT_ACCOUNT_ID] [int] NOT NULL,
	[DEMAT_ACCOUNT_VALUE] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[MUTUAL_FUND_PAYIN_PAYOUT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MUTUAL_FUND_PAYIN_PAYOUT] ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[LOGIN_INFO] ([LOGIN_INFO_ID])
GO
