CREATE TABLE [dbo].[MUTUAL_FUND_BUY](
	[MUTUAL_FUND_BUY_ID] [int] IDENTITY(1,1) NOT NULL,
	[MUTUAL_FUND_HEADER_ID] [int] NULL,
	[MUTUAL_FUND_AMOUNT] [decimal](6, 2) NULL,
	[MUTUAL_FUND_QUANTITY] [decimal](6, 2) NULL,
	[MUTUAL_FUND_BUY_DATE] [date] NULL,
	[MUTUAL_FUND_CHARGES] [decimal](6, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[MUTUAL_FUND_BUY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MUTUAL_FUND_BUY] ADD FOREIGN KEY([MUTUAL_FUND_HEADER_ID])
REFERENCES [dbo].[MUTUAL_FUND_HEADER] ([MUTUAL_FUND_HEADER_ID])
GO