CREATE TABLE [dbo].[SHARE_DIVIDEND](
	[SHARE_DIVIDEND_ID] [int] IDENTITY(1,1) NOT NULL,
	[SHARES_TRACKER_HEADER_ID] [int] NULL,
	[SHARES_PRICE_AMT] [decimal](6, 2) NOT NULL,
	[DIVIDEND_DATE] [date] NOT NULL,
	[SHARE_DESCRIPTION] VARCHAR(100) NULL, 
	[USER_ID] INT NOT NULL
    PRIMARY KEY CLUSTERED 
(
	[SHARE_DIVIDEND_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SHARE_DIVIDEND]  WITH CHECK ADD FOREIGN KEY([SHARES_TRACKER_HEADER_ID])
REFERENCES [dbo].[SHARES_TRACKER_HEADER] ([SHARES_TRACKER_HEADER_ID])
GO