CREATE TABLE [DBO].[SHARES_TRACKER_HEADER](
	[SHARES_TRACKER_HEADER_ID] [INT] IDENTITY(1,1) NOT NULL,
	[SHARES_NAME] [VARCHAR](500) NOT NULL,
	[SHARE_TYPE_CODE_ID] [INT] NULL,
	[SHARE_TYPE_CODE_VALUE] [VARCHAR](20) NULL,
	[USER_ID] [INT] NULL,
	[IS_INTRADAY] [BIT] NOT NULL,
	[SERVICE_CODE_ID] [INT] NOT NULL,
	[SERVICE_CODE_VALUE] [VARCHAR](20) NULL
PRIMARY KEY CLUSTERED 
(
	[SHARES_TRACKER_HEADER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [DBO].[SHARES_TRACKER_HEADER] ADD  DEFAULT ((0)) FOR [IS_INTRADAY]
Go

ALTER TABLE [SHARES_TRACKER_HEADER]  ADD FOREIGN KEY([USER_ID])
REFERENCES [DBO].[LOGIN_INFO] ([LOGIN_INFO_ID])
GO

