CREATE TRIGGER [DBO].[TRIGGER_DELIVERY_CHARGE]
ON [DBO].[SHARES_TRACKER_HEADER]
AFTER INSERT
AS
BEGIN
DECLARE @TABLE_ID INT 
DECLARE @USER_ID INT 
DECLARE @CHARGES INT 
	IF EXISTS (SELECT * FROM INSERTED WHERE SHARE_TYPE_CODE_VALUE = 'DELV' AND IS_INTRADAY = 0)
	BEGIN
		SELECT @TABLE_ID = SHARES_TRACKER_HEADER_ID FROM INSERTED
		SELECT @USER_ID = USER_ID FROM INSERTED
		SELECT @CHARGES = DATA1 FROM CODE_VALUE WHERE CODE_ID = 1 AND CODE_VALUE = 'DLCH'
		INSERT INTO [SHARES_TRACKER_EXTRA_CHARGES] VALUES (@CHARGES, 'DELIVERY CHARGES', GETDATE(), @TABLE_ID, 0, @USER_ID)
	END
END